# Generated by Django 5.2 on 2025-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField(verbose_name='Date Enregistrement')),
                ('societe', models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG')], max_length=50, verbose_name='Société')),
                ('banque', models.CharField(choices=[('BP', 'BP'), ('BMCE', 'BMCE')], max_length=50, verbose_name='Banque')),
                ('document', models.CharField(choices=[('Facture', 'Facture'), ('Avance', 'Avance'), ('Salaire', 'Salaire'), ('Impot', 'Impot')], max_length=50, verbose_name='Document')),
                ('fournisseurs', models.CharField(max_length=255, verbose_name='Fournisseurs')),
                ('numero_facture', models.CharField(blank=True, max_length=100, verbose_name='N° de facture')),
                ('due_date', models.DateField(verbose_name='Due Date / Ech Facture')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('$', '$'), ('MAD', 'MAD'), ('€', '€')], max_length=10, verbose_name='Devise')),
                ('mt_dhs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MT DHS')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
        ),
    ]
