# Generated by Django 5.2 on 2025-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Code Facture'),
        ),
    ]
