# Generated by Django 5.2 on 2025-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Code Facture'),
        ),
    ]
