# Generated by Django 5.2 on 2025-04-25 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='banque',
            field=models.CharField(choices=[('BP', 'BP'), ('BMCE', 'BMCE'), ('AWB', 'AWB'), ('CAM', 'CAM')], max_length=50, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.CharField(choices=[('Facture', 'Facture'), ('Avance', 'Avance'), ('Salaire', 'Salaire'), ('Impot', 'Impot'), ('Credit', 'Credit')], max_length=50, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='societe',
            field=models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS'), ('FMCG', 'FMCG')], max_length=50, verbose_name='Société'),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Priorité')),
                ('due_semaine', models.PositiveSmallIntegerField(verbose_name='Due Semaine')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_debit', models.DateField(blank=True, null=True, verbose_name='DATE DEBIT / Date De Paiement')),
                ('debite', models.BooleanField(default=False, verbose_name='Débité')),
                ('semaine_debit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semaine DEBIT')),
                ('p0_order', models.CharField(blank=True, max_length=50, verbose_name='P0 Order')),
                ('is_p0', models.BooleanField(default=False, verbose_name='Is P0')),
                ('payment_type', models.CharField(choices=[('regular', 'Regular'), ('finex', 'Finex')], max_length=10, verbose_name='Payment Type')),
                ('date_paiement_fournisseur', models.DateField(blank=True, null=True, verbose_name='DATE Paiement Fournisseur')),
                ('payment_semaine', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Payment Semaine')),
                ('nb_jours_finex', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nb Jours Finex')),
                ('date_ech_finex', models.DateField(blank=True, null=True, verbose_name='DATE ECH Finex')),
                ('ech_finex_semaine', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ech Finex Semaine')),
                ('statut_finex', models.CharField(blank=True, max_length=50, verbose_name='Statut Finex')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('$', '$'), ('MAD', 'MAD'), ('€', '€')], max_length=10, verbose_name='Devise')),
                ('fx_index', models.CharField(blank=True, max_length=20, verbose_name='SOFR / EURIBOR')),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Rate')),
                ('taux', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Taux')),
                ('taux_ajuste', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='TAUX AJUSTE')),
                ('refinance_en_dh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Refinance en DH')),
                ('refinance_en_devise', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Refinance en Devise')),
                ('interet', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='INTERET')),
                ('tx_interet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tx intérêt (%)')),
                ('interet_calcule', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Intérêt Calculé')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Difference')),
                ('theory_vs_real', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Theory VS Real')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='dashboard.invoice', verbose_name='Facture liée')),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
            },
        ),
    ]
