# Generated by Django 5.2 on 2025-05-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_invoice_banque_alter_invoice_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(max_length=100)),
                ('limit_finex', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taux_interet_finex', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interet_fix', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
