# Generated by Django 5.2 on 2025-05-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='custom_id',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='interet_fix',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bank',
            name='limit_finex',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='bank',
            name='taux_interet_finex',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
