# Generated by Django 5.2 on 2025-05-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_bank_custom_id_alter_bank_interet_fix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FX_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('rate_actual', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate_fcst_3m', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percent_3m', models.DecimalField(decimal_places=4, max_digits=6)),
                ('vol_3m', models.DecimalField(decimal_places=4, editable=False, max_digits=8)),
                ('value_adjusted', models.DecimalField(decimal_places=4, editable=False, max_digits=8)),
            ],
        ),
    ]
