# Generated by Django 5.2 on 2025-05-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_fx_hist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='limit_finex',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fx_hist',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')]),
        ),
        migrations.AlterField(
            model_name='fx_hist',
            name='percent_3m',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fx_hist',
            name='rate_actual',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fx_hist',
            name='rate_fcst_3m',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fx_hist',
            name='value_adjusted',
            field=models.DecimalField(decimal_places=10, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='fx_hist',
            name='vol_3m',
            field=models.DecimalField(decimal_places=10, editable=False, max_digits=30),
        ),
    ]
