# Generated by Django 5.2 on 2025-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_bank_limit_finex_alter_fx_hist_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fx_hist',
            name='refinancement_type',
            field=models.CharField(default='SOFR'),
            preserve_default=False,
        ),
    ]
