# Generated by Django 5.2 on 2025-05-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_fx_hist_refinancement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx_hist',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')]),
        ),
    ]
