# Generated by Django 5.2 on 2025-05-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_incomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='week',
        ),
    ]
