# Generated by Django 5.2 on 2025-05-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_incomes_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField()),
                ('societe', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=5, max_digits=30)),
                ('devise', models.CharField(max_length=10)),
                ('montant_dhs', models.DecimalField(decimal_places=5, max_digits=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField()),
                ('societe', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=5, max_digits=30)),
                ('devise', models.CharField(max_length=10)),
                ('montant_dhs', models.DecimalField(decimal_places=5, max_digits=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Impot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField()),
                ('societe', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=5, max_digits=30)),
                ('devise', models.CharField(max_length=10)),
                ('montant_dhs', models.DecimalField(decimal_places=5, max_digits=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField()),
                ('societe', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=5, max_digits=30)),
                ('devise', models.CharField(max_length=10)),
                ('montant_dhs', models.DecimalField(decimal_places=5, max_digits=30)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank')),
            ],
        ),
    ]
