# Generated by Django 5.2 on 2025-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_achat_financement_impot_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='societe',
            field=models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='financement',
            name='societe',
            field=models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='impot',
            name='societe',
            field=models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='societe',
            field=models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS')], max_length=100),
        ),
    ]
