# Generated by Django 5.2 on 2025-05-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_achat_societe_alter_financement_societe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='devise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='document',
            field=models.CharField(choices=[('Facture', 'Facture'), ('Avance', 'Avance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='financement',
            name='devise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='financement',
            name='document',
            field=models.CharField(choices=[('Credit', 'Credit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='financement',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='impot',
            name='devise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='impot',
            name='document',
            field=models.CharField(choices=[('TVA', 'TVA'), ('Account IS', 'Account IS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='impot',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='devise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='document',
            field=models.CharField(choices=[('Paie', 'Paie'), ('CNSS', 'CNSS'), ('IR', 'IR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
    ]
