# Generated by Django 5.2 on 2025-05-20 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_achat_devise_alter_achat_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impot',
            old_name='date_echeance',
            new_name='date_debit',
        ),
        migrations.RenameField(
            model_name='salaire',
            old_name='date_echeance',
            new_name='date_debit',
        ),
        migrations.RemoveField(
            model_name='impot',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='impot',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='impot',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='impot',
            name='numero_facture',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='numero_facture',
        ),
        migrations.AlterField(
            model_name='achat',
            name='date_enregistrement',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='financement',
            name='date_enregistrement',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='impot',
            name='date_enregistrement',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='date_enregistrement',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_enregistrement',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='date_enregistrement',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
