# Generated by Django 5.2 on 2025-05-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_date_echeance_impot_date_debit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financement',
            old_name='date_echeance',
            new_name='date_debit',
        ),
        migrations.RemoveField(
            model_name='financement',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='financement',
            name='numero_facture',
        ),
    ]
