# Generated by Django 5.2 on 2025-05-20 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_date_echeance_financement_date_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='dashboard.achat', verbose_name='Facture liée'),
        ),
        migrations.RemoveField(
            model_name='achat',
            name='date_echeance',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='achat',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due Date / Ech Facture'),
        ),
        migrations.AddField(
            model_name='achat',
            name='fournisseurs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fournisseurs'),
        ),
        migrations.AddField(
            model_name='achat',
            name='invoice_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Code Facture'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='banque',
            field=models.CharField(choices=[('BP', 'BP'), ('BMCE', 'BMCE'), ('AWB', 'AWB'), ('CAM', 'CAM')], max_length=50, verbose_name='Banque'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='devise',
            field=models.CharField(blank=True, choices=[('$', '$'), ('MAD', 'MAD'), ('€', '€')], max_length=10, null=True, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='document',
            field=models.CharField(choices=[('Facture', 'Facture'), ('Avance', 'Avance')], max_length=50, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_dhs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MT DHS'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de facture'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='societe',
            field=models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS'), ('FMCG', 'FMCG')], max_length=50, verbose_name='Société'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
