# Generated by Django 5.2 on 2025-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_achat_fournisseurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='date_debit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='date_echeance_effet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='date_echeance_finex',
            field=models.DateField(blank=True, editable=None, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='date_paiement_fournisseur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='debit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achat',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='interet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='interet_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='nb_jours_finex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='numero_effet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='payment_type',
            field=models.CharField(choices=[('courant', 'Courant'), ('finex', 'Finex'), ('effet', 'Effet')], default='courant', max_length=10),
        ),
        migrations.AddField(
            model_name='achat',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Priorité absolue (il faut payer immédiatement)'), (1, 'Priorité haute (à surveiller de près)'), (2, 'Priorité par défaut'), (3, 'Non prioritaire')], default=2),
        ),
        migrations.AddField(
            model_name='achat',
            name='statut_finex',
            field=models.CharField(blank=True, choices=[('exécute', 'Exécuté'), ('paid', 'Payé'), ('planifie', 'Planifié')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='taux_interet',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_dhs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant DHS'),
        ),
    ]
