# Generated by Django 5.2 on 2025-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_achat_date_debit_achat_date_echeance_effet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='statut_finex',
            field=models.CharField(blank=True, choices=[('exécute', 'Exécuté'), ('paid', 'Payé'), ('planifie', 'Planifié'), ('ajouter', 'ajouter')], max_length=20, null=True),
        ),
    ]
