# Generated by Django 5.2 on 2025-05-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_achat_difference_alter_achat_statut_finex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='interet_calcule',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='statut_finex',
            field=models.CharField(blank=True, choices=[('exécute', 'Exécuté'), ('paid', 'Payé'), ('planifie', 'Planifié'), ('initial', 'Initialisé (non planifié)')], default='initial', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='taux_interet',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=5, null=True),
        ),
    ]
