# Generated by Django 5.2 on 2025-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_achat_difference_alter_achat_interet_calcule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date_paiement_fournisseur',
            field=models.DateField(default='2025-05-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achat',
            name='nb_jours_finex',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
    ]
