# Generated by Django 5.2 on 2025-05-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_achat_date_paiement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date_paiement_fournisseur',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='nb_jours_finex',
            field=models.IntegerField(default=0),
        ),
    ]
