# Generated by Django 5.2 on 2025-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_achat_date_paiement_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='Finex',
            field=models.CharField(default='', max_length=50, verbose_name='Finex'),
            preserve_default=False,
        ),
    ]
