# Generated by Django 5.2 on 2025-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_achat_finex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Priorité absolue (il faut payer immédiatement)'), (1, 'Priorité haute (à surveiller de près)'), (2, 'Priorité Normal'), (3, 'Non prioritaire')], default=2),
        ),
    ]
