# Generated by Django 5.2 on 2025-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_achat_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='rate_actual',
            field=models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='refinancement_type',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='value_adjusted',
            field=models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=30, null=True),
        ),
    ]
