# Generated by Django 5.2 on 2025-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_achat_rate_actual_achat_refinancement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='Finex',
            field=models.CharField(default='-', max_length=50, verbose_name='Finex'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='devise',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('MAD', 'MAD'), ('USD', 'USD')], max_length=10, null=True, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='statut_finex',
            field=models.CharField(blank=True, choices=[('exécute', 'Exécuté'), ('paid', 'Payé'), ('planifie', 'Planifié'), ('initial', '-')], default='initial', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='devise',
            field=models.CharField(choices=[('EUR', 'EUR'), ('MAD', 'MAD'), ('USD', 'USD')], max_length=10, verbose_name='Devise'),
        ),
    ]
