# Generated by Django 5.2 on 2025-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_achat_finex_alter_achat_devise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='refine_sugg',
            field=models.CharField(blank=True, default='', editable=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='refine_used',
            field=models.CharField(blank=True, choices=[('En DH', 'Refine en DH'), ('EN Devise', 'Refine en Devise'), ('', 'NONE')], default='-', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='achat',
            name='taux',
            field=models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='banque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='interet_fix',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='limit_finex',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='taux_interet_finex',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
