# Generated by Django 5.2 on 2025-05-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_achat_refine_sugg_achat_refine_used_achat_taux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='banque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank'),
        ),
    ]
