# Generated by Django 5.2 on 2025-05-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_achat_banque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='rate_actual',
            new_name='percent_3m',
        ),
    ]
