# Generated by Django 5.2 on 2025-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_rename_rate_actual_achat_percent_3m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
    ]
