# Generated by Django 5.2 on 2025-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_achat_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='interet',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_dhs',
            field=models.DecimalField(decimal_places=2, default=0, editable=None, max_digits=12, verbose_name='Montant DHS'),
        ),
    ]
