# Generated by Django 5.2 on 2025-05-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_achat_difference_alter_achat_interet_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incomes',
            new_name='Income',
        ),
    ]
