# Generated by Django 5.2 on 2025-05-21 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_rename_incomes_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date_Income',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
