# Generated by Django 5.2 on 2025-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_income_date_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='banque',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
