# Generated by Django 5.2 on 2025-05-28 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_bank_banque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('Solde_date', models.DateField(default=django.utils.timezone.now)),
                ('societe', models.CharField(choices=[('AMAD', 'AMAD'), ('FMCG', 'FMCG'), ('AMAP', 'AMAP'), ('SULFO', 'SULFO'), ('ENGINUP', 'ENGINUP'), ('ENOSIS', 'ENOSIS'), ('LAC', 'LAC'), ('TODAYWORKS', 'TODAYWORKS'), ('FMCG', 'FMCG')], max_length=100)),
                ('montant_dhs', models.DecimalField(decimal_places=5, max_digits=30)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank')),
            ],
        ),
    ]
