# Generated by Django 5.2 on 2025-06-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='invoice_id',
            field=models.IntegerField(editable=False, unique=True, verbose_name='Code Facture'),
        ),
    ]
