# Generated by Django 5.2 on 2025-06-12 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_achat_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_effets', models.CharField(max_length=20)),
                ('n_remise', models.CharField(max_length=20)),
                ('reference_en_bd', models.CharField(blank=True, max_length=50, null=True)),
                ('date_decal', models.DateField(default=django.utils.timezone.now, verbose_name='date dépôt')),
                ('code_client', models.CharField(max_length=20)),
                ('nom_client', models.CharField(max_length=100)),
                ('montant_effet', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_decal_2', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'effet")),
                ('date_de_payement', models.DateField(default=django.utils.timezone.now)),
                ('escompte', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'En Cours')], max_length=10)),
                ('jours_retard', models.IntegerField(default=0, editable=False)),
                ('jours_escompte', models.IntegerField(default=0, editable=False)),
                ('Libere', models.BooleanField(default=0, editable=False, verbose_name='Libéré')),
                ('le_cout', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.bank')),
            ],
            options={
                'verbose_name': 'Escompte',
                'verbose_name_plural': 'Escomptes',
                'ordering': ['-date_decal'],
            },
        ),
    ]
