# Generated by Django 5.2 on 2025-06-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_escompte_escompte_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('last_update', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
