# Generated by Django 5.2 on 2025-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_tableupdatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escompte',
            name='date_de_payement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
